[tool.poetry]
name = "ubo-gui"
version = "0.6.2"
description = "GUI sdk for Ubo Pod"
authors = ["Sassan Haradji <sassanh@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{ include = "ubo_gui" }]
include = ['ubo_gui/assets/fonts/*']


[[tool.poetry.source]]
name = "piwheels"
url = "https://www.piwheels.org/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"


[tool.poetry.dependencies]
python = "^3.11"
headless-kivy-pi = [
  { version = "^0.5.1", markers = "extra!='dev'" },
  { version = "^0.5.1", markers = "extra=='dev'", extras = [
    "dev",
  ], optional = true },
]


[tool.poetry.group.dev.dependencies]
poethepoet = { version = "^0.24.2", markers = "platform_machine != 'aarch64'", source = 'PyPI' }
headless-kivy-pi = { version = "^0.5.1" }

[tool.poetry.extras]
dev = ['poethepoet', 'headless-kivy-pi']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
lint = "pyright -p pyproject.toml ."
download_font.shell = "mkdir -p ubo_gui/assets/fonts; wget https://github.com/google/material-design-icons/raw/master/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf -O ./ubo_gui/assets/fonts/MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf"

[tool.poe.tasks.deploy_to_device]
cmd = 'scripts/deploy.sh'

[tool.ruff]
select = ['ALL']
ignore = []

fixable = ['ALL']
unfixable = []

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[tool.ruff.format]
quote-style = 'single'
